ori:
	mkdir -p build
	g++ src/tables.c src/hash.c src/main.cpp src/sbox.c src/state.c -o build/main
	./build/main
o1:
	mkdir -p build
	g++ -O1 src/tables.c src/hash.c src/main.cpp src/sbox.c src/state.c -o build/main
	./build/main
o2:
	mkdir -p build
	g++ -O2 src/tables.c src/hash.c src/main.cpp src/sbox.c src/state.c -o build/main
	./build/main
o3:
	mkdir -p build
	g++ -O3 src/tables.c src/hash.c src/main.cpp src/sbox.c src/state.c -o build/main
	./build/main